### ISSUE TITLE
Link JSON Issue

### ISSUE THREAD

**Issue by Kaidriver** [JKSenthil/coronavirus-county-api#1]
The link doesn't seem to be working at the moment

**Comment by JKSenthil** [comment]
Hey! Actually, my project is deprecated, instead I have integrated this api here: https://github.com/ExpDev07/coronavirus-tracker-api

**Comment by Kaidriver** [comment]
Thank you for the response. I clicked on the new integrated API, but it seems like all the US county values are 0?

**Comment by JKSenthil** [comment]
Which values are 0? The https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs seems to work for me

**Comment by Kaidriver** [comment]
Oh it's working now, thank you! I think its the other source, jhu, that isn't working.
